title: Garrett Hayes
logo: "/images/logo.png?raw=true"
description: >
  <i>MSc (Computer Science), OSCP</i>
  <br><br>
  I am an Associate Teaching Professor at <a href="https://ontariotechu.ca/">Ontario Tech University</a>. Some of my focus areas include: 
  penetration testing, data science, applied mathematics, and sports physiology. 
  <br><br>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0
