title: Garrett Hayes
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an Associate Teaching Professor at Ontario Tech University. Some of my focus areas include: 
  penetration testing, cloud technologies, software-defined data centres, and applied mathematics. 
  <br><br>
  Second description 
  <br><br>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0
